name: Deploy to main
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'make install_deps && make binbot && make compress'
      - name: version
        run: echo "::set-output name=version::$(./bin/azblogfilter --version)"
        id: version
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*"
          token: ${{ secrets.GITHUB_TOKEN }}
